import { useState, useMemo } from 'react';
import { motion } from 'framer-motion';
import { Copy, Download, Check, Clock, Stethoscope, Loader2 } from 'lucide-react';
import Card from '../ui/Card';

function sanitizeText(text) {
  if (!text) return text;
  let s = text
    .replace(/\ufeff/g, '')
    .replace(/\u200b/g, '')
    .replace(/\u200c/g, '')
    .replace(/\u200d/g, '');
  s = s.replace(/[^\x20-\x7E\s\u00A0-\uD7FF\uE000-\uFFFD]/g, '');
  return s.trim();
}

export default function ClinicalNote({ note, onDownloadPDF, generating }) {
  const [copied, setCopied] = useState(false);
  const cleanNote = useMemo(() => sanitizeText(note), [note]);

  if (!cleanNote) {
    return (
      <Card variant="glass">
        <div style={{ textAlign: 'center', padding: '40px 20px' }}>
          <Stethoscope size={32} color="var(--text-muted)" style={{ marginBottom: 12, opacity: 0.4 }} />
          <p style={{ color: 'var(--text-muted)', fontSize: 14 }}>
            No clinical interpretation available.
          </p>
        </div>
      </Card>
    );
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(cleanNote);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* clipboard unavailable */ }
  };

  const handleDownload = () => {
    if (onDownloadPDF) {
      onDownloadPDF();
    } else {
      const blob = new Blob([cleanNote], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `lumina-clinical-report-${Date.now()}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  const formatNote = (text) => {
    return text
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\n{2,}/g, '\n\n')
      .split('\n').map((line, i) => {
        if (line.trim() === '') return null;
        const trimmed = line.trim();
        if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          return (
            <li key={i} style={{ marginBottom: 6, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
              {trimmed.substring(2)}
            </li>
          );
        }
        if (trimmed.startsWith('#')) {
          return (
            <h4 key={i} style={{ fontSize: 14, fontWeight: 600, color: 'var(--text-primary)', marginTop: 16, marginBottom: 8 }}>
              {trimmed.replace(/^#+\s*/, '')}
            </h4>
          );
        }
        return (
          <p key={i} style={{ marginBottom: 8, color: 'var(--text-secondary)', lineHeight: 1.7, fontSize: 13.5 }}>
            {trimmed}
          </p>
        );
      });
  };

  return (
    <Card variant="glass">
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: 16,
          paddingBottom: 12,
          borderBottom: '1px solid var(--border)',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <Stethoscope size={18} color="var(--accent)" />
          <div>
            <h3 style={{ fontSize: 15, fontWeight: 600, color: 'var(--text-primary)' }}>
              AI Clinical Interpretation
            </h3>
            <div style={{ display: 'flex', alignItems: 'center', gap: 4, marginTop: 2 }}>
              <Clock size={11} color="var(--text-muted)" />
              <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>
                Generated by Lumina AI · {new Date().toLocaleString()}
              </span>
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', gap: 6 }}>
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={handleCopy}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              padding: '6px 12px',
              borderRadius: 'var(--radius-sm)',
              background: copied ? 'var(--success-dim)' : 'var(--bg-primary)',
              border: `1px solid ${copied ? 'rgba(52,211,153,0.2)' : 'var(--border)'}`,
              color: copied ? 'var(--success)' : 'var(--text-secondary)',
              cursor: 'pointer',
              fontSize: 12,
              fontWeight: 500,
              transition: 'background 0.2s, color 0.2s',
            }}
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? 'Copied' : 'Copy'}
          </motion.button>
          <motion.button
            whileHover={generating ? {} : { scale: 1.05 }}
            whileTap={generating ? {} : { scale: 0.95 }}
            onClick={handleDownload}
            disabled={generating}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              padding: '6px 12px',
              borderRadius: 'var(--radius-sm)',
              background: generating ? 'var(--bg-surface)' : 'var(--bg-primary)',
              border: `1px solid ${generating ? 'var(--border)' : 'var(--border)'}`,
              color: generating ? 'var(--text-muted)' : 'var(--text-secondary)',
              cursor: generating ? 'not-allowed' : 'pointer',
              fontSize: 12,
              fontWeight: 500,
              fontFamily: 'inherit',
              transition: 'background 0.2s',
            }}
          >
            {generating ? <Loader2 size={14} className="spin-animation" /> : <Download size={14} />}
            {generating ? 'Generating...' : 'Download'}
          </motion.button>
        </div>
      </div>

      <div
        style={{
          maxHeight: 320,
          overflowY: 'auto',
          paddingRight: 4,
        }}
        className="scrollable-note"
      >
        <div>{formatNote(cleanNote)}</div>
      </div>
    </Card>
  );
}
